### ISSUE TITLE
Syntax problem

### ISSUE THREAD

**Issue by Mauri35** [GunGameOG/Discord-VPN-DDoS-Attack-Alerts#3]
Starting Attack Logs
./discordalerts.sh: line 11: -  : syntax error: operand expected (error token is "-  ")

**Comment by Mauri35** [comment]
HI! i have this problem, i running ubuntu 18.04 on a vps of Vultr to test it.
I fixed it by changing from this pkt= $(( $pkt_new - $pkt_old )) to this pkt= $( $pkt_new - $pkt_old )
I don't know if it works like this but now it gives me an error on line 16
![image](https://user-images.githubusercontent.com/76892508/122658663-7ffaf080-d146-11eb-98a9-dedc18dd0174.png)

**Comment by GunGameOG** [comment]
> HI! i have this problem, i running ubuntu 18.04 on a vps of Vultr to test it.
> I fixed it by changing from this pkt= $(( $pkt_new - $pkt_old )) to this pkt= $( $pkt_new - $pkt_old )
> I don't know if it works like this but now it gives me an error on line 16
> ![image](https://user-images.githubusercontent.com/76892508/122658663-7ffaf080-d146-11eb-98a9-dedc18dd0174.png)

I will check it out.

**Comment by GunGameOG** [comment]
> > HI! i have this problem, i running ubuntu 18.04 on a vps of Vultr to test it.
> > I fixed it by changing from this pkt= $(( $pkt_new - $pkt_old )) to this pkt= $( $pkt_new - $pkt_old )
> > I don't know if it works like this but now it gives me an error on line 16
> > ![image](https://user-images.githubusercontent.com/76892508/122658663-7ffaf080-d146-11eb-98a9-dedc18dd0174.png)
> 
> I will check it out.

Fixed
(![image](https://user-images.githubusercontent.com/58014273/122662225-41256480-d15f-11eb-9cbf-7caa56ffa6d8.png))

**Comment by Mauri35** [comment]
Thanks! Only one more query can be sent through the webhook, for example the incoming packets?

**Comment by GunGameOG** [comment]
I sends one notification when the attack is detected then after the attack has ended it sends another notification saying the attack was filtered. Message me on Discord GunGame-_OG#2881.
